# Generated by Django 2.2 on 2019-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rides',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('vehicle_model_id', models.IntegerField()),
                ('package_id', models.IntegerField()),
                ('travel_type_id', models.IntegerField()),
                ('from_area_id', models.IntegerField()),
                ('to_area_id', models.IntegerField()),
                ('from_city_id', models.IntegerField()),
                ('to_city_id', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('online_booking', models.BooleanField()),
                ('booking_created', models.DateTimeField()),
                ('from_lat', models.FloatField()),
                ('from_long', models.FloatField()),
                ('to_lat', models.FloatField()),
                ('to_long', models.FloatField()),
                ('Car_Cancellation', models.BooleanField()),
            ],
        ),
    ]
