# Generated by Django 2.2 on 2019-05-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xRides_api', '0003_rides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rides',
        ),
    ]
