# Generated by Django 2.2 on 2019-05-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xRides_api', '0004_delete_rides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_model_id', models.IntegerField(blank=True, null=True)),
                ('package_id', models.IntegerField(blank=True, null=True)),
                ('travel_type_id', models.IntegerField(blank=True, null=True)),
                ('from_area_id', models.IntegerField(blank=True, null=True)),
                ('to_area_id', models.IntegerField(blank=True, null=True)),
                ('from_city_id', models.IntegerField(blank=True, null=True)),
                ('to_city_id', models.IntegerField(blank=True, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('online_booking', models.BooleanField(blank=True, null=True)),
                ('mobile_site_booking', models.BooleanField(blank=True, null=True)),
                ('booking_created', models.DateTimeField(blank=True, null=True)),
                ('from_lat', models.FloatField(blank=True, null=True)),
                ('from_long', models.FloatField(blank=True, null=True)),
                ('to_lat', models.FloatField(blank=True, null=True)),
                ('to_long', models.FloatField(blank=True, null=True)),
                ('car_cancellation', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rides',
                'managed': False,
            },
        ),
    ]
